name: 'dbt_macaco'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_macaco'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
    "dbt_date:time_zone": "America/Sao_Paulo"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_macaco:
    staging:
      +materialized: view
    
    intermediate:
      +materialized: table
    
    mart:
      +materialized: table